### ISSUE TITLE
How can I bring all taxonomy terms under a parent menu

### ISSUE THREAD

**Issue by emfluenceindia** [unn/taxonomy_menu#6]
I am not sure if this should be added in issue queue at all. So sorry about it. May be marked as a feature request, if not somebody has already done it!

I created a `taxonomy-menu` with vocabulary `category` which has several taxonomy items defined under it. The configuration looks like:
```
Vocabulary -> Category
Menu -> Main Navigation
All menu entries -> Checked
Depth -> 1
Parent Menu Link -> Main Navigation
````
All taxonomy items are rendered as separate top level (level 0) menu items. My guess was it will use `Category` as parent item and under it the taxonomy terms will be added as sub-menu items.

Then I tried this:

```
Vocabulary -> Category
Menu -> Main Navigation
All menu entries -> Checked
Depth -> 1
Parent Menu Link -> Products
````
`/products` is a View page where all products get listed. In `Page view source` I did not see any taxonomy term got rendered.

Is there a way to do this?

NB: I rebuilt cache after making every change to `taxonomy-menu`.

**UPDATE:**
Because it creates separate menu items I dragged them under my `Products` menu from `/admin/structure/menu/manage/main` but after saving the tree structure resets and taxonomy menu items comes back under root.

**Comment by IngoVals** [comment]
Having same problem, this is a recent feature in 8.3.x and I assume we are talking about that. I raised the issue over at drupal.org

https://www.drupal.org/node/2723807#comment-11808659

**Comment by IngoVals** [comment]
Well suddenly it works for me and I'm not sure what I did differently.

@emfluenceindia I think your first mentioned method works as intended, if you want it to appear under Category parent you first have to create that item on the main menu and set it as the _Parent menu link_

In your second use case, is it possible that your main menu block has limited how many menu levels it shows. You should set it to Initial menu level 1 and maximum at 2 or higher.
